name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '**.json'
      - '**.yaml'
      - '**.yml'
  pull_request:
    branches: [main]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '**.json'
      - '**.yaml'
      - '**.yml'

permissions:
  contents: read

jobs:
  ci:
    name: Terraform CI
    uses: victron-venus/venus-os-ci-toolkit/.github/workflows/terraform-ci.yml@914ef58bbb7c711648d76b15af2c3c14db63771f
    with:
      working-directory: '.'
