name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  ci:
    name: Terraform CI
    uses: victron-venus/venus-os-ci-toolkit/.github/workflows/terraform-ci.yml@7f06318d7aa20453963cdd2485c5a09624a0955e
    with:
      working-directory: '.'
